import type { Metadata } from "next";
import "./globals.scss";
import { interRegular, interMedium, interBold, interExtraBold, interBlack } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interRegular.variable} ${interMedium.variable} ${interBold.variable} ${interExtraBold.variable} ${interBlack.variable}`}>
        {children}
      </body>
    </html>
  );
}
